#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 1
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 17

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_DOT = 2,
  anon_sym_LBRACK = 3,
  anon_sym_RBRACK = 4,
  anon_sym_LPAREN = 5,
  anon_sym_COMMA = 6,
  anon_sym_RPAREN = 7,
  sym_op_plus = 8,
  sym_op_mul = 9,
  sym_identifier = 10,
  sym_integer = 11,
  sym_source_file = 12,
  sym_bin_op = 13,
  sym_attribute = 14,
  sym_subscript = 15,
  sym_call = 16,
  sym_list = 17,
  sym_paren_expr = 18,
  sym_load = 19,
  sym_expression = 20,
  aux_sym_source_file_repeat1 = 21,
  aux_sym_call_repeat1 = 22,
  aux_sym_list_repeat1 = 23,
  anon_alias_sym_load = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_op_plus] = "op_plus",
  [sym_op_mul] = "op_mul",
  [sym_identifier] = "identifier",
  [sym_integer] = "integer",
  [sym_source_file] = "source_file",
  [sym_bin_op] = "bin_op",
  [sym_attribute] = "attribute",
  [sym_subscript] = "subscript",
  [sym_call] = "call",
  [sym_list] = "list",
  [sym_paren_expr] = "paren_expr",
  [sym_load] = "load",
  [sym_expression] = "expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [anon_alias_sym_load] = "load",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_op_plus] = sym_op_plus,
  [sym_op_mul] = sym_op_mul,
  [sym_identifier] = sym_identifier,
  [sym_integer] = sym_integer,
  [sym_source_file] = sym_source_file,
  [sym_bin_op] = sym_bin_op,
  [sym_attribute] = sym_attribute,
  [sym_subscript] = sym_subscript,
  [sym_call] = sym_call,
  [sym_list] = sym_list,
  [sym_paren_expr] = sym_paren_expr,
  [sym_load] = sym_load,
  [sym_expression] = sym_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [anon_alias_sym_load] = anon_alias_sym_load,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_op_plus] = {
    .visible = true,
    .named = true,
  },
  [sym_op_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_bin_op] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_subscript] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_load] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_load] = {
    .visible = true,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_elements = 2,
  field_exprs = 3,
  field_index = 4,
  field_left = 5,
  field_name = 6,
  field_operator = 7,
  field_right = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_elements] = "elements",
  [field_exprs] = "exprs",
  [field_index] = "index",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 2},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 2},
  [8] = {.index = 8, .length = 1},
  [9] = {.index = 9, .length = 3},
  [10] = {.index = 12, .length = 2},
  [11] = {.index = 14, .length = 2},
  [12] = {.index = 16, .length = 2},
  [13] = {.index = 18, .length = 2},
  [14] = {.index = 20, .length = 1},
  [15] = {.index = 21, .length = 3},
  [16] = {.index = 24, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_exprs, 0, .inherited = true},
  [1] =
    {field_exprs, 0},
  [2] =
    {field_exprs, 0, .inherited = true},
    {field_exprs, 1, .inherited = true},
  [4] =
    {field_elements, 1},
  [5] =
    {field_value, 1},
  [6] =
    {field_name, 2},
    {field_value, 0},
  [8] =
    {field_value, 0},
  [9] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [12] =
    {field_elements, 1},
    {field_elements, 2, .inherited = true},
  [14] =
    {field_elements, 0, .inherited = true},
    {field_elements, 1, .inherited = true},
  [16] =
    {field_index, 2},
    {field_value, 0},
  [18] =
    {field_arguments, 2},
    {field_value, 0},
  [20] =
    {field_arguments, 1},
  [21] =
    {field_arguments, 2},
    {field_arguments, 3, .inherited = true},
    {field_value, 0},
  [24] =
    {field_arguments, 0, .inherited = true},
    {field_arguments, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = anon_alias_sym_load,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == ')') ADVANCE(8);
      if (lookahead == '*') ADVANCE(10);
      if (lookahead == '+') ADVANCE(9);
      if (lookahead == ',') ADVANCE(7);
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == ';') ADVANCE(2);
      if (lookahead == '[') ADVANCE(4);
      if (lookahead == ']') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_op_plus);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_op_mul);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_op_plus] = ACTIONS(1),
    [sym_op_mul] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(37),
    [sym_bin_op] = STATE(16),
    [sym_attribute] = STATE(16),
    [sym_subscript] = STATE(16),
    [sym_call] = STATE(16),
    [sym_list] = STATE(16),
    [sym_paren_expr] = STATE(16),
    [sym_load] = STATE(16),
    [sym_expression] = STATE(31),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_integer] = ACTIONS(9),
  },
  [2] = {
    [sym_bin_op] = STATE(16),
    [sym_attribute] = STATE(16),
    [sym_subscript] = STATE(16),
    [sym_call] = STATE(16),
    [sym_list] = STATE(16),
    [sym_paren_expr] = STATE(16),
    [sym_load] = STATE(16),
    [sym_expression] = STATE(31),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(16),
    [sym_identifier] = ACTIONS(19),
    [sym_integer] = ACTIONS(22),
  },
  [3] = {
    [sym_bin_op] = STATE(16),
    [sym_attribute] = STATE(16),
    [sym_subscript] = STATE(16),
    [sym_call] = STATE(16),
    [sym_list] = STATE(16),
    [sym_paren_expr] = STATE(16),
    [sym_load] = STATE(16),
    [sym_expression] = STATE(31),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_integer] = ACTIONS(9),
  },
  [4] = {
    [sym_bin_op] = STATE(16),
    [sym_attribute] = STATE(16),
    [sym_subscript] = STATE(16),
    [sym_call] = STATE(16),
    [sym_list] = STATE(16),
    [sym_paren_expr] = STATE(16),
    [sym_load] = STATE(16),
    [sym_expression] = STATE(26),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_integer] = ACTIONS(9),
  },
  [5] = {
    [sym_bin_op] = STATE(16),
    [sym_attribute] = STATE(16),
    [sym_subscript] = STATE(16),
    [sym_call] = STATE(16),
    [sym_list] = STATE(16),
    [sym_paren_expr] = STATE(16),
    [sym_load] = STATE(16),
    [sym_expression] = STATE(25),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(29),
    [sym_identifier] = ACTIONS(7),
    [sym_integer] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      sym_integer,
    STATE(21), 1,
      sym_expression,
    STATE(16), 7,
      sym_bin_op,
      sym_attribute,
      sym_subscript,
      sym_call,
      sym_list,
      sym_paren_expr,
      sym_load,
  [25] = 6,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      sym_integer,
    STATE(30), 1,
      sym_expression,
    STATE(16), 7,
      sym_bin_op,
      sym_attribute,
      sym_subscript,
      sym_call,
      sym_list,
      sym_paren_expr,
      sym_load,
  [50] = 6,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      sym_integer,
    STATE(28), 1,
      sym_expression,
    STATE(16), 7,
      sym_bin_op,
      sym_attribute,
      sym_subscript,
      sym_call,
      sym_list,
      sym_paren_expr,
      sym_load,
  [75] = 6,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      sym_integer,
    STATE(27), 1,
      sym_expression,
    STATE(16), 7,
      sym_bin_op,
      sym_attribute,
      sym_subscript,
      sym_call,
      sym_list,
      sym_paren_expr,
      sym_load,
  [100] = 6,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      sym_integer,
    STATE(29), 1,
      sym_expression,
    STATE(16), 7,
      sym_bin_op,
      sym_attribute,
      sym_subscript,
      sym_call,
      sym_list,
      sym_paren_expr,
      sym_load,
  [125] = 6,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      sym_integer,
    STATE(24), 1,
      sym_expression,
    STATE(16), 7,
      sym_bin_op,
      sym_attribute,
      sym_subscript,
      sym_call,
      sym_list,
      sym_paren_expr,
      sym_load,
  [150] = 1,
    ACTIONS(31), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [162] = 1,
    ACTIONS(33), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [174] = 1,
    ACTIONS(35), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [186] = 1,
    ACTIONS(37), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [198] = 1,
    ACTIONS(39), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [210] = 1,
    ACTIONS(41), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [222] = 1,
    ACTIONS(43), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [234] = 1,
    ACTIONS(45), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [246] = 1,
    ACTIONS(47), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [258] = 4,
    ACTIONS(51), 1,
      anon_sym_DOT,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 6,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [276] = 1,
    ACTIONS(57), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [288] = 1,
    ACTIONS(59), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [300] = 5,
    ACTIONS(51), 1,
      anon_sym_DOT,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_op_mul,
    ACTIONS(49), 5,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
  [320] = 8,
    ACTIONS(51), 1,
      anon_sym_DOT,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_op_mul,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_RPAREN,
    ACTIONS(67), 1,
      sym_op_plus,
    STATE(35), 1,
      aux_sym_call_repeat1,
  [345] = 8,
    ACTIONS(51), 1,
      anon_sym_DOT,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_op_mul,
    ACTIONS(67), 1,
      sym_op_plus,
    ACTIONS(69), 1,
      anon_sym_RBRACK,
    ACTIONS(71), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      aux_sym_list_repeat1,
  [370] = 6,
    ACTIONS(51), 1,
      anon_sym_DOT,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_op_mul,
    ACTIONS(67), 1,
      sym_op_plus,
    ACTIONS(73), 2,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [390] = 6,
    ACTIONS(51), 1,
      anon_sym_DOT,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_op_mul,
    ACTIONS(67), 1,
      sym_op_plus,
    ACTIONS(75), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [410] = 6,
    ACTIONS(51), 1,
      anon_sym_DOT,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_op_mul,
    ACTIONS(67), 1,
      sym_op_plus,
    ACTIONS(77), 1,
      anon_sym_RBRACK,
  [429] = 6,
    ACTIONS(51), 1,
      anon_sym_DOT,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_op_mul,
    ACTIONS(67), 1,
      sym_op_plus,
    ACTIONS(79), 1,
      anon_sym_RPAREN,
  [448] = 6,
    ACTIONS(51), 1,
      anon_sym_DOT,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_op_mul,
    ACTIONS(67), 1,
      sym_op_plus,
    ACTIONS(81), 1,
      anon_sym_SEMI,
  [467] = 1,
    ACTIONS(83), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_identifier,
      sym_integer,
  [475] = 3,
    ACTIONS(71), 1,
      anon_sym_COMMA,
    ACTIONS(85), 1,
      anon_sym_RBRACK,
    STATE(34), 1,
      aux_sym_list_repeat1,
  [485] = 3,
    ACTIONS(87), 1,
      anon_sym_RBRACK,
    ACTIONS(89), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      aux_sym_list_repeat1,
  [495] = 3,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      aux_sym_call_repeat1,
  [505] = 3,
    ACTIONS(94), 1,
      anon_sym_COMMA,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      aux_sym_call_repeat1,
  [515] = 1,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
  [519] = 1,
    ACTIONS(101), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 25,
  [SMALL_STATE(8)] = 50,
  [SMALL_STATE(9)] = 75,
  [SMALL_STATE(10)] = 100,
  [SMALL_STATE(11)] = 125,
  [SMALL_STATE(12)] = 150,
  [SMALL_STATE(13)] = 162,
  [SMALL_STATE(14)] = 174,
  [SMALL_STATE(15)] = 186,
  [SMALL_STATE(16)] = 198,
  [SMALL_STATE(17)] = 210,
  [SMALL_STATE(18)] = 222,
  [SMALL_STATE(19)] = 234,
  [SMALL_STATE(20)] = 246,
  [SMALL_STATE(21)] = 258,
  [SMALL_STATE(22)] = 276,
  [SMALL_STATE(23)] = 288,
  [SMALL_STATE(24)] = 300,
  [SMALL_STATE(25)] = 320,
  [SMALL_STATE(26)] = 345,
  [SMALL_STATE(27)] = 370,
  [SMALL_STATE(28)] = 390,
  [SMALL_STATE(29)] = 410,
  [SMALL_STATE(30)] = 429,
  [SMALL_STATE(31)] = 448,
  [SMALL_STATE(32)] = 467,
  [SMALL_STATE(33)] = 475,
  [SMALL_STATE(34)] = 485,
  [SMALL_STATE(35)] = 495,
  [SMALL_STATE(36)] = 505,
  [SMALL_STATE(37)] = 515,
  [SMALL_STATE(38)] = 519,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4), SHIFT_REPEAT(4),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4), SHIFT_REPEAT(7),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4), SHIFT_REPEAT(20),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4), SHIFT_REPEAT(16),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, .production_id = 2),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, .production_id = 8),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, .production_id = 15),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, .production_id = 13),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subscript, 4, .production_id = 12),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, .production_id = 10),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, .production_id = 5),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_load, 1, .production_id = 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bin_op, 3, .production_id = 9),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 3, .production_id = 6),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, .production_id = 7),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 5),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 14),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 11),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 11), SHIFT_REPEAT(9),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 16), SHIFT_REPEAT(8),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 16),
  [99] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_toytest() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
