#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 38
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 16

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_DOT = 2,
  anon_sym_LBRACK = 3,
  anon_sym_RBRACK = 4,
  anon_sym_LPAREN = 5,
  anon_sym_COMMA = 6,
  anon_sym_RPAREN = 7,
  sym_op_plus = 8,
  sym_op_mul = 9,
  sym_identifier = 10,
  sym_integer = 11,
  sym_source_file = 12,
  sym_bin_op = 13,
  sym_attribute = 14,
  sym_subscript = 15,
  sym_call = 16,
  sym_list = 17,
  sym_paren_expr = 18,
  sym_expression = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym_call_repeat1 = 21,
  aux_sym_list_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_op_plus] = "op_plus",
  [sym_op_mul] = "op_mul",
  [sym_identifier] = "identifier",
  [sym_integer] = "integer",
  [sym_source_file] = "source_file",
  [sym_bin_op] = "bin_op",
  [sym_attribute] = "attribute",
  [sym_subscript] = "subscript",
  [sym_call] = "call",
  [sym_list] = "list",
  [sym_paren_expr] = "paren_expr",
  [sym_expression] = "expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_op_plus] = sym_op_plus,
  [sym_op_mul] = sym_op_mul,
  [sym_identifier] = sym_identifier,
  [sym_integer] = sym_integer,
  [sym_source_file] = sym_source_file,
  [sym_bin_op] = sym_bin_op,
  [sym_attribute] = sym_attribute,
  [sym_subscript] = sym_subscript,
  [sym_call] = sym_call,
  [sym_list] = sym_list,
  [sym_paren_expr] = sym_paren_expr,
  [sym_expression] = sym_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_op_plus] = {
    .visible = true,
    .named = true,
  },
  [sym_op_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_bin_op] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_subscript] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_elements = 2,
  field_exprs = 3,
  field_index = 4,
  field_left = 5,
  field_name = 6,
  field_operator = 7,
  field_right = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_elements] = "elements",
  [field_exprs] = "exprs",
  [field_index] = "index",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 3},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 2},
  [12] = {.index = 18, .length = 2},
  [13] = {.index = 20, .length = 1},
  [14] = {.index = 21, .length = 3},
  [15] = {.index = 24, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_exprs, 0, .inherited = true},
  [1] =
    {field_exprs, 0},
  [2] =
    {field_exprs, 0, .inherited = true},
    {field_exprs, 1, .inherited = true},
  [4] =
    {field_elements, 1},
  [5] =
    {field_value, 1},
  [6] =
    {field_name, 2},
    {field_value, 0},
  [8] =
    {field_value, 0},
  [9] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [12] =
    {field_elements, 1},
    {field_elements, 2, .inherited = true},
  [14] =
    {field_elements, 0, .inherited = true},
    {field_elements, 1, .inherited = true},
  [16] =
    {field_index, 2},
    {field_value, 0},
  [18] =
    {field_arguments, 2},
    {field_value, 0},
  [20] =
    {field_arguments, 1},
  [21] =
    {field_arguments, 2},
    {field_arguments, 3, .inherited = true},
    {field_value, 0},
  [24] =
    {field_arguments, 0, .inherited = true},
    {field_arguments, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == ')') ADVANCE(8);
      if (lookahead == '*') ADVANCE(10);
      if (lookahead == '+') ADVANCE(9);
      if (lookahead == ',') ADVANCE(7);
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == ';') ADVANCE(2);
      if (lookahead == '[') ADVANCE(4);
      if (lookahead == ']') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_op_plus);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_op_mul);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_op_plus] = ACTIONS(1),
    [sym_op_mul] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(37),
    [sym_bin_op] = STATE(19),
    [sym_attribute] = STATE(19),
    [sym_subscript] = STATE(19),
    [sym_call] = STATE(19),
    [sym_list] = STATE(19),
    [sym_paren_expr] = STATE(19),
    [sym_expression] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_integer] = ACTIONS(7),
  },
  [2] = {
    [sym_bin_op] = STATE(19),
    [sym_attribute] = STATE(19),
    [sym_subscript] = STATE(19),
    [sym_call] = STATE(19),
    [sym_list] = STATE(19),
    [sym_paren_expr] = STATE(19),
    [sym_expression] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(14),
    [sym_identifier] = ACTIONS(17),
    [sym_integer] = ACTIONS(17),
  },
  [3] = {
    [sym_bin_op] = STATE(19),
    [sym_attribute] = STATE(19),
    [sym_subscript] = STATE(19),
    [sym_call] = STATE(19),
    [sym_list] = STATE(19),
    [sym_paren_expr] = STATE(19),
    [sym_expression] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(20),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_integer] = ACTIONS(7),
  },
  [4] = {
    [sym_bin_op] = STATE(19),
    [sym_attribute] = STATE(19),
    [sym_subscript] = STATE(19),
    [sym_call] = STATE(19),
    [sym_list] = STATE(19),
    [sym_paren_expr] = STATE(19),
    [sym_expression] = STATE(25),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_RBRACK] = ACTIONS(22),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_integer] = ACTIONS(7),
  },
  [5] = {
    [sym_bin_op] = STATE(19),
    [sym_attribute] = STATE(19),
    [sym_subscript] = STATE(19),
    [sym_call] = STATE(19),
    [sym_list] = STATE(19),
    [sym_paren_expr] = STATE(19),
    [sym_expression] = STATE(24),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(24),
    [sym_identifier] = ACTIONS(7),
    [sym_integer] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    STATE(30), 1,
      sym_expression,
    ACTIONS(7), 2,
      sym_identifier,
      sym_integer,
    STATE(19), 6,
      sym_bin_op,
      sym_attribute,
      sym_subscript,
      sym_call,
      sym_list,
      sym_paren_expr,
  [22] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_expression,
    ACTIONS(7), 2,
      sym_identifier,
      sym_integer,
    STATE(19), 6,
      sym_bin_op,
      sym_attribute,
      sym_subscript,
      sym_call,
      sym_list,
      sym_paren_expr,
  [44] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    STATE(26), 1,
      sym_expression,
    ACTIONS(7), 2,
      sym_identifier,
      sym_integer,
    STATE(19), 6,
      sym_bin_op,
      sym_attribute,
      sym_subscript,
      sym_call,
      sym_list,
      sym_paren_expr,
  [66] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_expression,
    ACTIONS(7), 2,
      sym_identifier,
      sym_integer,
    STATE(19), 6,
      sym_bin_op,
      sym_attribute,
      sym_subscript,
      sym_call,
      sym_list,
      sym_paren_expr,
  [88] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    STATE(20), 1,
      sym_expression,
    ACTIONS(7), 2,
      sym_identifier,
      sym_integer,
    STATE(19), 6,
      sym_bin_op,
      sym_attribute,
      sym_subscript,
      sym_call,
      sym_list,
      sym_paren_expr,
  [110] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_expression,
    ACTIONS(7), 2,
      sym_identifier,
      sym_integer,
    STATE(19), 6,
      sym_bin_op,
      sym_attribute,
      sym_subscript,
      sym_call,
      sym_list,
      sym_paren_expr,
  [132] = 4,
    ACTIONS(28), 1,
      anon_sym_DOT,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(26), 6,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [150] = 1,
    ACTIONS(34), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [162] = 1,
    ACTIONS(36), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [174] = 1,
    ACTIONS(38), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [186] = 1,
    ACTIONS(40), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [198] = 1,
    ACTIONS(42), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [210] = 1,
    ACTIONS(44), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [222] = 1,
    ACTIONS(46), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [234] = 5,
    ACTIONS(28), 1,
      anon_sym_DOT,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      sym_op_mul,
    ACTIONS(26), 5,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
  [254] = 1,
    ACTIONS(50), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [266] = 1,
    ACTIONS(52), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [278] = 1,
    ACTIONS(54), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_op_plus,
      sym_op_mul,
  [290] = 8,
    ACTIONS(28), 1,
      anon_sym_DOT,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      sym_op_mul,
    ACTIONS(56), 1,
      anon_sym_COMMA,
    ACTIONS(58), 1,
      anon_sym_RPAREN,
    ACTIONS(60), 1,
      sym_op_plus,
    STATE(34), 1,
      aux_sym_call_repeat1,
  [315] = 8,
    ACTIONS(28), 1,
      anon_sym_DOT,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      sym_op_mul,
    ACTIONS(60), 1,
      sym_op_plus,
    ACTIONS(62), 1,
      anon_sym_RBRACK,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym_list_repeat1,
  [340] = 6,
    ACTIONS(28), 1,
      anon_sym_DOT,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      sym_op_mul,
    ACTIONS(60), 1,
      sym_op_plus,
    ACTIONS(66), 2,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [360] = 6,
    ACTIONS(28), 1,
      anon_sym_DOT,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      sym_op_mul,
    ACTIONS(60), 1,
      sym_op_plus,
    ACTIONS(68), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [380] = 6,
    ACTIONS(28), 1,
      anon_sym_DOT,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      sym_op_mul,
    ACTIONS(60), 1,
      sym_op_plus,
    ACTIONS(70), 1,
      anon_sym_RBRACK,
  [399] = 6,
    ACTIONS(28), 1,
      anon_sym_DOT,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      sym_op_mul,
    ACTIONS(60), 1,
      sym_op_plus,
    ACTIONS(72), 1,
      anon_sym_SEMI,
  [418] = 6,
    ACTIONS(28), 1,
      anon_sym_DOT,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      sym_op_mul,
    ACTIONS(60), 1,
      sym_op_plus,
    ACTIONS(74), 1,
      anon_sym_RPAREN,
  [437] = 1,
    ACTIONS(76), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym_identifier,
      sym_integer,
  [445] = 3,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    ACTIONS(78), 1,
      anon_sym_RBRACK,
    STATE(33), 1,
      aux_sym_list_repeat1,
  [455] = 3,
    ACTIONS(80), 1,
      anon_sym_RBRACK,
    ACTIONS(82), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      aux_sym_list_repeat1,
  [465] = 3,
    ACTIONS(56), 1,
      anon_sym_COMMA,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    STATE(35), 1,
      aux_sym_call_repeat1,
  [475] = 3,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(90), 1,
      anon_sym_RPAREN,
    STATE(35), 1,
      aux_sym_call_repeat1,
  [485] = 1,
    ACTIONS(92), 1,
      sym_identifier,
  [489] = 1,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 22,
  [SMALL_STATE(8)] = 44,
  [SMALL_STATE(9)] = 66,
  [SMALL_STATE(10)] = 88,
  [SMALL_STATE(11)] = 110,
  [SMALL_STATE(12)] = 132,
  [SMALL_STATE(13)] = 150,
  [SMALL_STATE(14)] = 162,
  [SMALL_STATE(15)] = 174,
  [SMALL_STATE(16)] = 186,
  [SMALL_STATE(17)] = 198,
  [SMALL_STATE(18)] = 210,
  [SMALL_STATE(19)] = 222,
  [SMALL_STATE(20)] = 234,
  [SMALL_STATE(21)] = 254,
  [SMALL_STATE(22)] = 266,
  [SMALL_STATE(23)] = 278,
  [SMALL_STATE(24)] = 290,
  [SMALL_STATE(25)] = 315,
  [SMALL_STATE(26)] = 340,
  [SMALL_STATE(27)] = 360,
  [SMALL_STATE(28)] = 380,
  [SMALL_STATE(29)] = 399,
  [SMALL_STATE(30)] = 418,
  [SMALL_STATE(31)] = 437,
  [SMALL_STATE(32)] = 445,
  [SMALL_STATE(33)] = 455,
  [SMALL_STATE(34)] = 465,
  [SMALL_STATE(35)] = 475,
  [SMALL_STATE(36)] = 485,
  [SMALL_STATE(37)] = 489,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3), SHIFT_REPEAT(4),
  [14] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3), SHIFT_REPEAT(6),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3), SHIFT_REPEAT(19),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, .production_id = 1),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bin_op, 3, .production_id = 8),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subscript, 4, .production_id = 11),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, .production_id = 14),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, .production_id = 12),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, .production_id = 9),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, .production_id = 4),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 3, .production_id = 5),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, .production_id = 6),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, .production_id = 7),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 4),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 13),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 10),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 10), SHIFT_REPEAT(8),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 15), SHIFT_REPEAT(7),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 15),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [94] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_toytest() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
