#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 1
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 18

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_DOT = 2,
  anon_sym_LBRACK = 3,
  anon_sym_RBRACK = 4,
  anon_sym_LPAREN = 5,
  anon_sym_COMMA = 6,
  anon_sym_RPAREN = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_DOLLAR = 10,
  sym_op_plus = 11,
  sym_op_mul = 12,
  sym_identifier = 13,
  sym_integer = 14,
  sym_source_file = 15,
  sym_bin_op = 16,
  sym_attribute = 17,
  sym_subscript = 18,
  sym_call = 19,
  sym_list = 20,
  sym_paren_expr = 21,
  sym_load = 22,
  sym__brace_expr = 23,
  sym_brace_expr = 24,
  sym__dollar_expr = 25,
  sym_dollar_expr = 26,
  sym_expression = 27,
  aux_sym_source_file_repeat1 = 28,
  aux_sym_call_repeat1 = 29,
  aux_sym_list_repeat1 = 30,
  anon_alias_sym_load = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOLLAR] = "$",
  [sym_op_plus] = "op_plus",
  [sym_op_mul] = "op_mul",
  [sym_identifier] = "identifier",
  [sym_integer] = "integer",
  [sym_source_file] = "source_file",
  [sym_bin_op] = "bin_op",
  [sym_attribute] = "attribute",
  [sym_subscript] = "subscript",
  [sym_call] = "call",
  [sym_list] = "list",
  [sym_paren_expr] = "paren_expr",
  [sym_load] = "load",
  [sym__brace_expr] = "paren_expr",
  [sym_brace_expr] = "brace_expr",
  [sym__dollar_expr] = "dollar_expr",
  [sym_dollar_expr] = "dollar_expr",
  [sym_expression] = "expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [anon_alias_sym_load] = "load",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_op_plus] = sym_op_plus,
  [sym_op_mul] = sym_op_mul,
  [sym_identifier] = sym_identifier,
  [sym_integer] = sym_integer,
  [sym_source_file] = sym_source_file,
  [sym_bin_op] = sym_bin_op,
  [sym_attribute] = sym_attribute,
  [sym_subscript] = sym_subscript,
  [sym_call] = sym_call,
  [sym_list] = sym_list,
  [sym_paren_expr] = sym_paren_expr,
  [sym_load] = sym_load,
  [sym__brace_expr] = sym_paren_expr,
  [sym_brace_expr] = sym_brace_expr,
  [sym__dollar_expr] = sym__dollar_expr,
  [sym_dollar_expr] = sym_dollar_expr,
  [sym_expression] = sym_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [anon_alias_sym_load] = anon_alias_sym_load,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_op_plus] = {
    .visible = true,
    .named = true,
  },
  [sym_op_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_bin_op] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_subscript] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_load] = {
    .visible = true,
    .named = true,
  },
  [sym__brace_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_brace_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__dollar_expr] = {
    .visible = true,
    .named = false,
  },
  [sym_dollar_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_load] = {
    .visible = true,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_elements = 2,
  field_exprs = 3,
  field_index = 4,
  field_left = 5,
  field_name = 6,
  field_operator = 7,
  field_right = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_elements] = "elements",
  [field_exprs] = "exprs",
  [field_index] = "index",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 1},
  [5] = {.index = 3, .length = 2},
  [6] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 1},
  [8] = {.index = 7, .length = 2},
  [9] = {.index = 9, .length = 1},
  [10] = {.index = 10, .length = 3},
  [11] = {.index = 13, .length = 2},
  [12] = {.index = 15, .length = 2},
  [13] = {.index = 17, .length = 2},
  [14] = {.index = 19, .length = 2},
  [15] = {.index = 21, .length = 1},
  [16] = {.index = 22, .length = 3},
  [17] = {.index = 25, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_value, 0, .inherited = true},
  [1] =
    {field_exprs, 0, .inherited = true},
  [2] =
    {field_exprs, 0},
  [3] =
    {field_exprs, 0, .inherited = true},
    {field_exprs, 1, .inherited = true},
  [5] =
    {field_elements, 1},
  [6] =
    {field_value, 1},
  [7] =
    {field_name, 2},
    {field_value, 0},
  [9] =
    {field_value, 0},
  [10] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [13] =
    {field_elements, 1},
    {field_elements, 2, .inherited = true},
  [15] =
    {field_elements, 0, .inherited = true},
    {field_elements, 1, .inherited = true},
  [17] =
    {field_index, 2},
    {field_value, 0},
  [19] =
    {field_arguments, 2},
    {field_value, 0},
  [21] =
    {field_arguments, 1},
  [22] =
    {field_arguments, 2},
    {field_arguments, 3, .inherited = true},
    {field_value, 0},
  [25] =
    {field_arguments, 0, .inherited = true},
    {field_arguments, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = anon_alias_sym_load,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '$') ADVANCE(11);
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == ')') ADVANCE(8);
      if (lookahead == '*') ADVANCE(13);
      if (lookahead == '+') ADVANCE(12);
      if (lookahead == ',') ADVANCE(7);
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == ';') ADVANCE(2);
      if (lookahead == '[') ADVANCE(4);
      if (lookahead == ']') ADVANCE(5);
      if (lookahead == '{') ADVANCE(9);
      if (lookahead == '}') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_op_plus);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_op_mul);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_op_plus] = ACTIONS(1),
    [sym_op_mul] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(46),
    [sym_bin_op] = STATE(25),
    [sym_attribute] = STATE(25),
    [sym_subscript] = STATE(25),
    [sym_call] = STATE(25),
    [sym_list] = STATE(25),
    [sym_paren_expr] = STATE(25),
    [sym_load] = STATE(25),
    [sym__brace_expr] = STATE(24),
    [sym_brace_expr] = STATE(25),
    [sym__dollar_expr] = STATE(17),
    [sym_dollar_expr] = STATE(25),
    [sym_expression] = STATE(37),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
  },
  [2] = {
    [sym_bin_op] = STATE(25),
    [sym_attribute] = STATE(25),
    [sym_subscript] = STATE(25),
    [sym_call] = STATE(25),
    [sym_list] = STATE(25),
    [sym_paren_expr] = STATE(25),
    [sym_load] = STATE(25),
    [sym__brace_expr] = STATE(24),
    [sym_brace_expr] = STATE(25),
    [sym__dollar_expr] = STATE(17),
    [sym_dollar_expr] = STATE(25),
    [sym_expression] = STATE(37),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(20),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_DOLLAR] = ACTIONS(26),
    [sym_identifier] = ACTIONS(29),
    [sym_integer] = ACTIONS(32),
  },
  [3] = {
    [sym_bin_op] = STATE(25),
    [sym_attribute] = STATE(25),
    [sym_subscript] = STATE(25),
    [sym_call] = STATE(25),
    [sym_list] = STATE(25),
    [sym_paren_expr] = STATE(25),
    [sym_load] = STATE(25),
    [sym__brace_expr] = STATE(24),
    [sym_brace_expr] = STATE(25),
    [sym__dollar_expr] = STATE(17),
    [sym_dollar_expr] = STATE(25),
    [sym_expression] = STATE(37),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
  },
  [4] = {
    [sym_bin_op] = STATE(25),
    [sym_attribute] = STATE(25),
    [sym_subscript] = STATE(25),
    [sym_call] = STATE(25),
    [sym_list] = STATE(25),
    [sym_paren_expr] = STATE(25),
    [sym_load] = STATE(25),
    [sym__brace_expr] = STATE(24),
    [sym_brace_expr] = STATE(25),
    [sym__dollar_expr] = STATE(17),
    [sym_dollar_expr] = STATE(25),
    [sym_expression] = STATE(32),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_RBRACK] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
  },
  [5] = {
    [sym_bin_op] = STATE(25),
    [sym_attribute] = STATE(25),
    [sym_subscript] = STATE(25),
    [sym_call] = STATE(25),
    [sym_list] = STATE(25),
    [sym_paren_expr] = STATE(25),
    [sym_load] = STATE(25),
    [sym__brace_expr] = STATE(24),
    [sym_brace_expr] = STATE(25),
    [sym__dollar_expr] = STATE(17),
    [sym_dollar_expr] = STATE(25),
    [sym_expression] = STATE(31),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(39),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
  },
  [6] = {
    [sym_bin_op] = STATE(25),
    [sym_attribute] = STATE(25),
    [sym_subscript] = STATE(25),
    [sym_call] = STATE(25),
    [sym_list] = STATE(25),
    [sym_paren_expr] = STATE(25),
    [sym_load] = STATE(25),
    [sym__brace_expr] = STATE(24),
    [sym_brace_expr] = STATE(25),
    [sym__dollar_expr] = STATE(17),
    [sym_dollar_expr] = STATE(25),
    [sym_expression] = STATE(20),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
  },
  [7] = {
    [sym_bin_op] = STATE(25),
    [sym_attribute] = STATE(25),
    [sym_subscript] = STATE(25),
    [sym_call] = STATE(25),
    [sym_list] = STATE(25),
    [sym_paren_expr] = STATE(25),
    [sym_load] = STATE(25),
    [sym__brace_expr] = STATE(24),
    [sym_brace_expr] = STATE(25),
    [sym__dollar_expr] = STATE(17),
    [sym_dollar_expr] = STATE(25),
    [sym_expression] = STATE(40),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
  },
  [8] = {
    [sym_bin_op] = STATE(25),
    [sym_attribute] = STATE(25),
    [sym_subscript] = STATE(25),
    [sym_call] = STATE(25),
    [sym_list] = STATE(25),
    [sym_paren_expr] = STATE(25),
    [sym_load] = STATE(25),
    [sym__brace_expr] = STATE(24),
    [sym_brace_expr] = STATE(25),
    [sym__dollar_expr] = STATE(17),
    [sym_dollar_expr] = STATE(25),
    [sym_expression] = STATE(39),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
  },
  [9] = {
    [sym_bin_op] = STATE(25),
    [sym_attribute] = STATE(25),
    [sym_subscript] = STATE(25),
    [sym_call] = STATE(25),
    [sym_list] = STATE(25),
    [sym_paren_expr] = STATE(25),
    [sym_load] = STATE(25),
    [sym__brace_expr] = STATE(24),
    [sym_brace_expr] = STATE(25),
    [sym__dollar_expr] = STATE(17),
    [sym_dollar_expr] = STATE(25),
    [sym_expression] = STATE(38),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
  },
  [10] = {
    [sym_bin_op] = STATE(25),
    [sym_attribute] = STATE(25),
    [sym_subscript] = STATE(25),
    [sym_call] = STATE(25),
    [sym_list] = STATE(25),
    [sym_paren_expr] = STATE(25),
    [sym_load] = STATE(25),
    [sym__brace_expr] = STATE(24),
    [sym_brace_expr] = STATE(25),
    [sym__dollar_expr] = STATE(17),
    [sym_dollar_expr] = STATE(25),
    [sym_expression] = STATE(33),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
  },
  [11] = {
    [sym_bin_op] = STATE(25),
    [sym_attribute] = STATE(25),
    [sym_subscript] = STATE(25),
    [sym_call] = STATE(25),
    [sym_list] = STATE(25),
    [sym_paren_expr] = STATE(25),
    [sym_load] = STATE(25),
    [sym__brace_expr] = STATE(24),
    [sym_brace_expr] = STATE(25),
    [sym__dollar_expr] = STATE(17),
    [sym_dollar_expr] = STATE(25),
    [sym_expression] = STATE(35),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
  },
  [12] = {
    [sym_bin_op] = STATE(25),
    [sym_attribute] = STATE(25),
    [sym_subscript] = STATE(25),
    [sym_call] = STATE(25),
    [sym_list] = STATE(25),
    [sym_paren_expr] = STATE(25),
    [sym_load] = STATE(25),
    [sym__brace_expr] = STATE(24),
    [sym_brace_expr] = STATE(25),
    [sym__dollar_expr] = STATE(17),
    [sym_dollar_expr] = STATE(25),
    [sym_expression] = STATE(19),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
  },
  [13] = {
    [sym_bin_op] = STATE(25),
    [sym_attribute] = STATE(25),
    [sym_subscript] = STATE(25),
    [sym_call] = STATE(25),
    [sym_list] = STATE(25),
    [sym_paren_expr] = STATE(25),
    [sym_load] = STATE(25),
    [sym__brace_expr] = STATE(24),
    [sym_brace_expr] = STATE(25),
    [sym__dollar_expr] = STATE(17),
    [sym_dollar_expr] = STATE(25),
    [sym_expression] = STATE(36),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(41), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [14] = 1,
    ACTIONS(43), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [28] = 1,
    ACTIONS(45), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [42] = 1,
    ACTIONS(47), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [56] = 1,
    ACTIONS(49), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [70] = 4,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 8,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [90] = 5,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      sym_op_mul,
    ACTIONS(51), 7,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
  [112] = 1,
    ACTIONS(61), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [126] = 1,
    ACTIONS(63), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [140] = 1,
    ACTIONS(65), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [154] = 1,
    ACTIONS(67), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [168] = 1,
    ACTIONS(69), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [182] = 1,
    ACTIONS(71), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [196] = 1,
    ACTIONS(73), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [210] = 1,
    ACTIONS(75), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [224] = 1,
    ACTIONS(77), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [238] = 1,
    ACTIONS(79), 11,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_op_plus,
      sym_op_mul,
  [252] = 8,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      sym_op_mul,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    ACTIONS(85), 1,
      sym_op_plus,
    STATE(42), 1,
      aux_sym_call_repeat1,
  [277] = 8,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      sym_op_mul,
    ACTIONS(85), 1,
      sym_op_plus,
    ACTIONS(87), 1,
      anon_sym_RBRACK,
    ACTIONS(89), 1,
      anon_sym_COMMA,
    STATE(43), 1,
      aux_sym_list_repeat1,
  [302] = 6,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      sym_op_mul,
    ACTIONS(85), 1,
      sym_op_plus,
    ACTIONS(91), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [322] = 1,
    ACTIONS(93), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      sym_identifier,
      sym_integer,
  [332] = 6,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      sym_op_mul,
    ACTIONS(85), 1,
      sym_op_plus,
    ACTIONS(95), 2,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [352] = 6,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      sym_op_mul,
    ACTIONS(85), 1,
      sym_op_plus,
    ACTIONS(97), 1,
      anon_sym_RBRACK,
  [371] = 6,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      sym_op_mul,
    ACTIONS(85), 1,
      sym_op_plus,
    ACTIONS(99), 1,
      anon_sym_SEMI,
  [390] = 6,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      sym_op_mul,
    ACTIONS(85), 1,
      sym_op_plus,
    ACTIONS(101), 1,
      anon_sym_DOLLAR,
  [409] = 6,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      sym_op_mul,
    ACTIONS(85), 1,
      sym_op_plus,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
  [428] = 6,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      sym_op_mul,
    ACTIONS(85), 1,
      sym_op_plus,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
  [447] = 3,
    ACTIONS(107), 1,
      anon_sym_RBRACK,
    ACTIONS(109), 1,
      anon_sym_COMMA,
    STATE(41), 1,
      aux_sym_list_repeat1,
  [457] = 3,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      aux_sym_call_repeat1,
  [467] = 3,
    ACTIONS(89), 1,
      anon_sym_COMMA,
    ACTIONS(114), 1,
      anon_sym_RBRACK,
    STATE(41), 1,
      aux_sym_list_repeat1,
  [477] = 3,
    ACTIONS(116), 1,
      anon_sym_COMMA,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      aux_sym_call_repeat1,
  [487] = 1,
    ACTIONS(121), 1,
      sym_identifier,
  [491] = 1,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 14,
  [SMALL_STATE(16)] = 28,
  [SMALL_STATE(17)] = 42,
  [SMALL_STATE(18)] = 56,
  [SMALL_STATE(19)] = 70,
  [SMALL_STATE(20)] = 90,
  [SMALL_STATE(21)] = 112,
  [SMALL_STATE(22)] = 126,
  [SMALL_STATE(23)] = 140,
  [SMALL_STATE(24)] = 154,
  [SMALL_STATE(25)] = 168,
  [SMALL_STATE(26)] = 182,
  [SMALL_STATE(27)] = 196,
  [SMALL_STATE(28)] = 210,
  [SMALL_STATE(29)] = 224,
  [SMALL_STATE(30)] = 238,
  [SMALL_STATE(31)] = 252,
  [SMALL_STATE(32)] = 277,
  [SMALL_STATE(33)] = 302,
  [SMALL_STATE(34)] = 322,
  [SMALL_STATE(35)] = 332,
  [SMALL_STATE(36)] = 352,
  [SMALL_STATE(37)] = 371,
  [SMALL_STATE(38)] = 390,
  [SMALL_STATE(39)] = 409,
  [SMALL_STATE(40)] = 428,
  [SMALL_STATE(41)] = 447,
  [SMALL_STATE(42)] = 457,
  [SMALL_STATE(43)] = 467,
  [SMALL_STATE(44)] = 477,
  [SMALL_STATE(45)] = 487,
  [SMALL_STATE(46)] = 491,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 5),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 5), SHIFT_REPEAT(4),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 5), SHIFT_REPEAT(7),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 5), SHIFT_REPEAT(8),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 5), SHIFT_REPEAT(9),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 5), SHIFT_REPEAT(22),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 5), SHIFT_REPEAT(25),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, .production_id = 3),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, .production_id = 9),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subscript, 4, .production_id = 13),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dollar_expr, 1, .production_id = 2),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, .production_id = 11),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bin_op, 3, .production_id = 10),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, .production_id = 16),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_load, 1, .production_id = 1),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, .production_id = 6),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_expr, 1, .production_id = 2),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 3, .production_id = 7),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__brace_expr, 3, .production_id = 7),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dollar_expr, 3, .production_id = 7),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, .production_id = 8),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, .production_id = 14),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 15),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 6),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 12),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(11),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 17), SHIFT_REPEAT(10),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, .production_id = 17),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [123] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_toytest() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
